image: maven:3-jdk-8

stages:
- build
- deploy
- tag

maven_build:
  stage: build
  script:
     - mvn clean package
  artifacts:
     paths:
     - target/*.jar
     expire_in: 10d
  only:
    - master