image: maven:3-jdk-8

stages:
- build
- deploy

ProtectionLib:
  stage: build
  script:
     - mvn clean package
  artifacts:
     paths:
     - target/*.jar
  only:
    - master
    
ProtectionLib-Nexus:
  stage: deploy
  script:
     - mvn deploy
  only:
    - master