image: maven:3-jdk-8

stages:
- build
- tag
- deploy

ProtectionLib:
  stage: build
  script:
     - mvn clean package
  artifacts:
     paths:
     - target/*.jar
  only:
    - master
    
deploy:
  script:
    - 'cp ci_settings.xml /root/.m2/settings.xml'
    - 'mvn deploy'
  only:
    - master
  image: maven:3.3.9-jdk-8