image: maven:3-jdk-8

stages:
- build
- tag
- deploy

ProtectionLib:
  stage: build
  script:
     - mvn clean package
  artifacts:
     paths:
     - target/*.jar
  only:
    - master
    
ProtectionLib-Nexus:
  stage: deploy
  script:
     - mvn deploy -U -Dmaven.test.skip=true -Duser=admin -Dpassword=aoSC4YKV651b706
  only:
    - master