image: maven:3-openjdk-16

stages:
- build

ProtectionLib:
  stage: build
  script:
     - mvn clean package -Dfurniture.tag="-dev-$CI_COMMIT_SHORT_SHA" -e
  artifacts:
     paths:
     - target/*.jar
  only:
    - master