image: maven:3.8.1-jdk-16

stages:
- build

ProtectionLib:
  stage: build
  script:
     - mvn clean package -Dfurniture.tag="-dev-$CI_COMMIT_SHORT_SHA"
  artifacts:
     paths:
     - target/*.jar
  only:
    - master