language: java
jdk:
  - oraclejdk8
before_script:
    mkdir lib/
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib
script:
    - mvn -B verify
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  
install: true