language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - /v\d+\.\d+[a-z]/
script:
  - mvn clean package
env:
  matrix:
  - version=0.9.7-Snapshot
before_install:
- export TRAVIS_TAG=${version}
- mvn versions:set -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -DnewVersion=${TRAVIS_TAG:1}
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  api-key: "${GITHUB_TOKEN}"
  file_glob: true
  file:
  - /home/travis/build/Ste3et/ProtectionLib/target/ProtectionLib*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  prerelease: true
cache:
  directories:
  - "$HOME/.m2"