language: java
jdk:
  - oraclejdk8
before_script:
    mkdir -p lib/
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/GLib.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/IslandWorld.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/Kingdoms.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/Landlord-v2.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/PlotSquared.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/PreciousStones-1.12.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/Residence4.8.0.2.jar
    wget -P "lib/" https://github.com/Ste3et/ProtectionLib/raw/master/lib/Towny.jar
script:
    - mvn -B verify
install: true