language: java
jdk: oraclejdk8
script:
  - mvn clean package
env:
  matrix:
  - MC=1.13
before_install:
- mvn versions:set -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -DnewVersion=${TRAVIS_TAG:1}
deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file_glob: true
  file:
  - /home/travis/build/Ste3et/ProtectionLib/target/ProtectionLib*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  prerelease: true
cache:
  directories:
  - "$HOME/.m2"