name: ProtectionLib
version: 0.4
description: NA
author: Ste3et_C0st
website: http://dicecraft.de
softdepend: [WorldGuard, Plotz, PlotMe, PlotSquared, Towny, GriefPrevention, Landlord, uSkyBlock, aSkyBlock, RedProtect, Residence, Vault]
main: de.Ste3et_C0st.ProtectionLib.main.ProtectionLib

permissions:
  ProtectionLib.admin: true