name: ProtectionLib
version: 0.8
description: NA
author: Ste3et_C0st
website: http://dicecraft.de
softdepend: [WorldGuard, Plotz, PlotMe, PlotSquared, Towny, PreciousStones, GriefPrevention, Landlord, uSkyBlock, ASkyBlock, aSkyBlock, Skyblock_Extra, React, EssentialsSpawn, RedProtect, Residence, Vault]
main: de.Ste3et_C0st.ProtectionLib.main.ProtectionLib

permissions:
  ProtectionLib.admin:
    description: "Permission to place furnitures without acces."
    default: op